title: "AWS Hands-on for Beginners Amazon EC2 Auto Scalingスケーリング基礎編ハンズオン手順書"
summary: "2021/10/13開催 JAWS-UG金沢支部×初心者支部 コラボイベント https://jawsug-kanazawa.doorkeeper.jp/events/128283 で実施するハンズオンの手順書になります。
https://pages.awscloud.com/JAPAN-event-OE-Hands-on-for-Beginners-Auto_Scaling-2021-reg-event.html?trk=aws_introduction_page で紹介されております資料をもとに一部アレンジしています。"
topics: ["AWS", "EC2"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - 1-introduction
  - 2-create-environment
  - 3-launch-template
  - 4-scaleout
  - 5-scalein
  - 6-instancereplacement
  - 9-clean-up
