title: "AWS Hands-on for Beginners Amazon EC2 Auto Scalingスケーリング基礎編ハンズオン手順書"
summary: "2021/10/13開催 JAWS-UG金沢支部×初心者支部 コラボイベント で実施するハンズオンの手順書になります。
https://pages.awscloud.com/JAPAN-event-OE-Hands-on-for-Beginners-Auto_Scaling-2021-reg-event.html?trk=aws_introduction_page で紹介されております資料をもとに作成しています"
topics: ["AWS", "EC2"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - 1-introduction
  - 2-create-environment
  - 9-clean-up
